/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.redaction-observer.jsonc --include-runtime=false --env-interface=RedactionObserverEnv src/redaction-observer-configuration.d.ts` (hash: cb7f51d46b8fe32d685cb3f51dd4df9d)
interface __BaseEnv_RedactionObserverEnv {
	REDACTION_SUMMARY: DurableObjectNamespace<import("./redaction-observer").RedactionSummary>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./redaction-observer");
		durableNamespaces: "RedactionSummary";
	}
	interface Env extends __BaseEnv_RedactionObserverEnv {}
}
interface RedactionObserverEnv extends __BaseEnv_RedactionObserverEnv {}
